apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "paw.fullname" . }}-config
  labels:
    {{- include "paw.labels" . | nindent 4 }}
data:
  chain-id: {{ .Values.node.chainId | quote }}
  moniker: {{ .Values.node.moniker | quote }}
  min-gas-prices: {{ .Values.node.minGasPrices | quote }}
  log-level: {{ .Values.node.logLevel | quote }}
  log-format: {{ .Values.node.logFormat | quote }}
  prometheus-metrics: {{ .Values.node.prometheusMetrics | quote }}
