apiVersion: v1
kind: Service
metadata:
  name: {{ include "paw.fullname" . }}
  labels:
    {{- include "paw.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.ports.p2p.port }}
      targetPort: {{ .Values.service.ports.p2p.targetPort }}
      protocol: {{ .Values.service.ports.p2p.protocol }}
      name: p2p
    - port: {{ .Values.service.ports.rpc.port }}
      targetPort: {{ .Values.service.ports.rpc.targetPort }}
      protocol: {{ .Values.service.ports.rpc.protocol }}
      name: rpc
    - port: {{ .Values.service.ports.api.port }}
      targetPort: {{ .Values.service.ports.api.targetPort }}
      protocol: {{ .Values.service.ports.api.protocol }}
      name: api
    - port: {{ .Values.service.ports.grpc.port }}
      targetPort: {{ .Values.service.ports.grpc.targetPort }}
      protocol: {{ .Values.service.ports.grpc.protocol }}
      name: grpc
    {{- if .Values.node.prometheusMetrics }}
    - port: {{ .Values.service.ports.metrics.port }}
      targetPort: {{ .Values.service.ports.metrics.targetPort }}
      protocol: {{ .Values.service.ports.metrics.protocol }}
      name: metrics
    {{- end }}
  selector:
    {{- include "paw.selectorLabels" . | nindent 4 }}
