blank_issues_enabled: false
contact_links:
  - name: Security Vulnerability
    url: https://github.com/poaiw-blockchain/paw/security/advisories/new
    about: Report security issues privately
  - name: Questions & Support
    url: https://discord.gg/paw
    about: Get help on Discord
