apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: paw-validators

resources:
  - statefulset.yaml
  - services.yaml
  - pdb.yaml
  - servicemonitor.yaml

commonLabels:
  app.kubernetes.io/component: validator
