apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: paw-base

namespace: paw

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/name: paw
      app.kubernetes.io/part-of: paw-network
      app.kubernetes.io/managed-by: kustomize

resources:
  - namespace.yaml
  - rbac.yaml
  - storage-class.yaml
  - network-policies.yaml

commonLabels:
  app.kubernetes.io/name: paw

commonAnnotations:
  app.kubernetes.io/version: "1.0.0"
